# utils/logging.py
LOGGING_DEFAULT_LOG_NAME = "heytechnonia"
LOGGING_DEFAULT_LOG_LEVEL = "DEBUG"
LOGGING_DEFAULT_CONSOLE_LOG_LEVEL = "INFO"
LOGGING_DEFAULT_MAX_BYTES = 10485760
LOGGING_DEFAULT_BACKUP_COUNT = 10
LOGGING_DEFAULT_LOGGING_WORKERS = 1
